# Generated by Django 3.1.4 on 2020-12-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=10, verbose_name='标签名称'),
        ),
    ]
