# Generated by Django 3.1.4 on 2021-01-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog_app', '0002_auto_20201231_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pv',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='uv',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.PositiveIntegerField(choices=[(2, '编辑'), (1, '正常'), (0, '删除')], verbose_name='文章状态'),
        ),
    ]
