# Generated by Django 3.1.4 on 2021-01-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog_app', '0003_auto_20210106_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='context_html',
            field=models.TextField(blank=True, editable=False, verbose_name='正文html代码'),
        ),
    ]
